### PR TITLE
Add Rigid Body description

### PR DESCRIPTION
**Pull request by fmrico**
Dear MOCAP4ROS2 developers,

This PR contains a proposal for a rigid body message.

Please, check your mocap systems that this is coherent, or if you need more fields.

Best
Francisco

Signed-off-by: Francisco Martín Rico <fmrico@gmail.com>

### CODE REVIEW

**Review by jmguerreroh — COMMENTED** [review]
We can include the name, and optional the number of markers associated with the rigid body. In optitrack this information is included in sRigidBodyDescription

**Comment by MFernandezCarmona** [comment]
I agree with @jmguerreroh . In vicon rigid bodies are called "objects": virtual sets of markers with a given name. So both fields are also relevant in Vicon systems ("name" and list of marker names).

**Comment by fmrico** [comment]
Hi!!

I have added a field:

```
int64[] markers_indexes
```

Is this enough? Should the index markers be an int, or maybe a string?

Best

**Comment by MFernandezCarmona** [comment]
+1 to String. At least that's the way they are identified in VICON

**Comment by jmguerreroh** [comment]
Using NatNetSDK, RigidBody's name is identified as string, but the number of markers associated with the rigid body should be int32. 

I would include in that msg a string and an int32, and we can discuss including a new msg containing a RigidBody's array.

**Review by MFernandezCarmona — APPROVED** [review]

**Comment by fmrico** [comment]
Dear devs,

Ok, I have changed int by string. I would not maintain both, as @jmguerreroh suggested.

Best

**Comment by fmrico** [comment]
I will merge now. This implies changes on the drivers @aarsht7 @jmguerreroh @MFernandezCarmona :wink:

**Comment by aarsht7** [comment]
Hello @jmguerreroh , I want to know the purpose of `string[ ] markers_indexes` with respect to optitrack system. 

There is possibilities to get the number of associated markers with the rigidbody but that will be an integer. AFAIK there will not be any other data of those markers in the sRigidBodyDescription. For that we will have to filter the Labeled markers with the rigidbody ID. So according to me, one important field to include in the Rigidbody.msg will be an ID of the rigidbody. That will be double (according to the sample code). And we can use that ID and use the Markers.msg to publish the msg under the rigidbody name. Something similar that I did in [this driver](https://github.com/L2S-lab/natnet_ros_cpp)

> Markers of the rigid bodies are published ad geometry_msgs/PointStamped unuder the name /natnet_ros/body-name/marker#/pose

@MFernandezCarmona Let us know if it is something similar in the Vicon as well.
@fmrico Let us know your views on including the ID within the msg.

**Comment by jmguerreroh** [comment]
Hi @aarsht7, I probably did not explain well, but I suggest including the RigidBody's name as a string and the number of markers associated with the rigid body as an integer. Then, why do you think is not useful to include the name in RigidBody.msg? I think this allows us to use this msg independently of Markers.msg

**Comment by aarsht7** [comment]
Hello @jmguerreroh , I understood the RigidBody's name as a string and the number of markers associated with the rigid body as an integer and I agree with that. I wanted to know more about the use of `string[ ] markers_indexes` with respect to optitrack system. And I saw your msg related to optitrack system so I thought I can ask to you. Sorry if the message was confusing 😅

**Pull request merged**
